### ISSUE TITLE
NoSuchMethodError in AbstractBigMathFunction.evaluate line 48

### ISSUE THREAD

**Issue by mvsoder** [ezylang/EvalEx-big-math#14]
Since the release of EvalEx 3.3.0 this method in EvalEx-big-math 1.0.0 is no longer valid due to an argument mismatch:

java.lang.NoSuchMethodError: 'void com.ezylang.evalex.data.EvaluationValue.<init>(java.lang.Object)'
	at com.ezylang.evalex.bigmath.functions.bigdecimalmath.AbstractBigMathFunction.evaluate(AbstractBigMathFunction.java:48)

**Comment by JellyBrick** [comment]
Bump
